[package]
name = "jvmti"
version = "0.3.0"
authors = [ "Alex Pecsi <xea@blacklight.so>" ]
description = "Rust bindings for the JVM TI"
keywords = [ "java", "jvm", "jvmti", "debugger" ]

[lib]
crate_type = [ "dylib", "rlib" ]

[dependencies]
libc = "0.2.*"
time = "0.1.34"
lazy_static = "0.1.*"
