[package]
name = "agent"
version = "0.3.0"
authors = [ "Alex Pecsi <xea@blacklight.so>" ]
keywords = [ "java", "jvm", "jvmti", "debugger" ]

[dependencies]
jvmti = { path = "../jvmti" }
libc = "0.2.*"
time = "0.1.34"
lazy_static = "0.1.*"
